#include "AIPlayer.h"

using namespace std;

// Author: Jan Mizera
// Implements an AI player that uses the Proximal Policy Optimization (PPO) algorithm.
// This class is responsible for making decisions during the Monopoly game based on the encoded game state
// and action masks generated by the Codec class.

// Take turn by selecting actions until rolling the dice_______________________________________________________________

DiceResult AIPlayer::takeTurn() {
    int actions_this_turn = 0;
    const int max_actions = 100;

    while( true ) {
        if( actions_this_turn++ > max_actions ) {
            has_pending_experience_ = false;
            return rollDice();
        }

        unsigned int action_id = getDecisionFromBrain( GamePhase::MY_TURN );

        if( action_id == ROLL_DICE_ID ) {
            has_pending_experience_ = false;
            return rollDice();
        }

        try {
            if( action_id >= BUILD_HOUSE_ID_START && action_id < SELL_HOUSE_ID_START ) {
                unsigned int idx = action_id - BUILD_HOUSE_ID_START;
                Property* prop = getPropertyByIndex( idx );
                if( prop && prop->getOwner() == this ) {
                    build( *prop );
                }
            } else if( action_id >= SELL_HOUSE_ID_START && action_id < MORTGAGE_ID_START ) {
                unsigned int idx = action_id - SELL_HOUSE_ID_START;
                Property* prop = getPropertyByIndex( idx );
                if( prop && prop->getOwner() == this && prop->getHouseCount() > 0 ) {
                    addCash( prop->getHouseCost() / 2 );
                    prop->decreaseBuildingLevel();
                }
            } else if( action_id >= MORTGAGE_ID_START && action_id < UNMORTGAGE_ID_START ) {
                unsigned int idx = action_id - MORTGAGE_ID_START;
                PurchasableCard* card = getPurchasableByIndex( idx );
                if( card && card->getOwner() == this && !card->isMortgaged() ) {
                    mortgageCard( *card );
                }
            } else if( action_id >= UNMORTGAGE_ID_START && action_id < AUCTION_BID_ID ) {
                unsigned int idx = action_id - UNMORTGAGE_ID_START;
                PurchasableCard* card = getPurchasableByIndex( idx );
                if( card && card->getOwner() == this && card->isMortgaged() ) {
                    unmortgageCard( *card );
                }
            }
        } catch( const exception& e ) {
            cerr << "[AI] Error executing action " << action_id << ": " << e.what() << "\n";
            return rollDice();
        }
    }
}

// Decide whether to use Get Out of Jail Free card_____________________________________________________________________

bool AIPlayer::useGetOutOfJailCard() {
    arma::colvec state =
        Codec::encodeGameState( *players_, *board_, *playerPositions_, this, GamePhase::JAIL_DECISION );
    arma::colvec action_mask =
        Codec::getActionMask( *players_, *board_, *playerPositions_, this, GamePhase::JAIL_DECISION );
    unsigned int action_id = getDecisionFromBrain( GamePhase::JAIL_DECISION );

    return action_id == USE_GET_OUT_OF_JAIL_CARD_ID;
}

// Decide whether to buy a property or let it go to auction____________________________________________________________

PlayerDecision AIPlayer::decideBuyOrAuction( const PurchasableCard& card ) {
    arma::colvec state = Codec::encodeGameState( *players_, *board_, *playerPositions_, this, GamePhase::BUY_DECISION );
    arma::colvec action_mask =
        Codec::getActionMask( *players_, *board_, *playerPositions_, this, GamePhase::BUY_DECISION );
    unsigned int action_id = getDecisionFromBrain( GamePhase::BUY_DECISION );

    if( action_id == BUY_PROPERTY_ID ) {
        return PlayerDecision::BUY;
    } else {
        return PlayerDecision::AUCTION;
    }
}

// Decide whether to bid in an auction, depending on the current highest bid and the property being auctioned__________

unsigned int AIPlayer::decideBid( const PurchasableCard& card, unsigned int current_bid ) {
    arma::colvec state = Codec::encodeGameState( *players_, *board_, *playerPositions_, this, GamePhase::BIDDING );
    int per_player_size = POSITION + CASH + JAIL_STATUS + JAIL_PROGRESS + GAME_STATUS + GET_OUT_OF_JAIL_CARDS;
    int per_property_size = OWNERSHIP + TYPE + MORTGAGE_STATUS + HOUSE_COUNT + HOTEL_COUNT + MONOPOLY_STATUS;

    int auctions_offset =
        PHASE + ACTIVE_PLAYER_IDX + ( PLAYERS * per_player_size ) + ( PROPERTIES * per_property_size );
    int property_index = 0;
    bool found = false;
    for( const auto& space : *board_ ) {
        Card* c = space->getAssociatedCard();
        if( auto* p_card = dynamic_cast<PurchasableCard*>( c ) ) {
            if( p_card->getName() == card.getName() ) {
                found = true;
                break;
            }
            ++property_index;
        }
    }
    if( found && property_index < PROPERTIES ) {
        state( auctions_offset + property_index ) = 1.0;
    }
    int bid_value_offset = auctions_offset + PROPERTIES;
    state( bid_value_offset ) = static_cast<double>( current_bid ) / 1500.0;

    arma::colvec action_mask =
        Codec::getActionMask( *players_, *board_, *playerPositions_, this, GamePhase::BIDDING, current_bid );

    double reward = calculateReward();

    unsigned int action_id = getDecisionFromBrain( state, action_mask, reward );

    if( action_id == AUCTION_BID_ID ) {
        return current_bid + BID_INCREMENT;
    }
    return 0;
}

// Roll the dice_______________________________________________________________________________________________________

DiceResult AIPlayer::rollDice() const {
    DiceResult result;
    result.die1_ = ( rand() % 6 ) + 1;
    result.die2_ = ( rand() % 6 ) + 1;
    return result;
}

// Call the overloaded getDecisionFromBrain method_____________________________________________________________________

unsigned int AIPlayer::getDecisionFromBrain( GamePhase phase, unsigned int extra_context ) {
    arma::colvec current_state = Codec::encodeGameState( *players_, *board_, *playerPositions_, this, phase );
    arma::colvec current_mask =
        Codec::getActionMask( *players_, *board_, *playerPositions_, this, phase, extra_context );

    double reward = calculateReward();

    return getDecisionFromBrain( current_state, current_mask, reward );
}

// Get the decision from the model_____________________________________________________________________________________

unsigned int AIPlayer::getDecisionFromBrain( const arma::colvec& state, const arma::colvec& mask, double reward ) {
    if( is_training_ && has_pending_experience_ ) {
        trainer_->recordExperience( last_state_, last_mask_, last_action_, reward, state, false );
        has_pending_experience_ = false;
    }

    unsigned int action_id = trainer_->predictAction( state, mask );

    last_state_ = state;
    last_mask_ = mask;
    last_action_ = action_id;
    has_pending_experience_ = true;

    return action_id;
}

// NOP_________________________________________________________________________________________________________________

void AIPlayer::informOfRandomCard( const RandomCard& card ) {}

// Set the trainer_____________________________________________________________________________________________________

void AIPlayer::setTrainer( TrainingManager* trainer ) {
    trainer_ = trainer;
}

// Calculate the reward based on change in total wealth________________________________________________________________

double AIPlayer::calculateReward() {
    double total_wealth = getCash();
    for( const Card* card : getOwnedCards() ) {
        const PurchasableCard* p_card = dynamic_cast<const PurchasableCard*>( card );
        if( p_card ) {
            total_wealth += static_cast<double>( p_card->getPrice() );
        }
    }

    double reward = ( total_wealth - prev_wealth_ ) / STARTING_CASH;
    prev_wealth_ = total_wealth;
    return reward;
}

// Notify the AI about the end of the game_____________________________________________________________________________

void AIPlayer::notifyGameEnd( bool is_draw ) {
    if( is_training_ && has_pending_experience_ ) {
        double final_reward = calculateReward();
        if( is_draw ) {
            final_reward -= 2.5;
        } else if( !isLost() ) {
            final_reward += 10.0;
        } else {
            final_reward -= 10.0;
        }
        trainer_->recordExperience( last_state_, last_mask_, last_action_, final_reward, last_state_, true );
        has_pending_experience_ = false;
    }
}

// Set training mode___________________________________________________________________________________________________

void AIPlayer::setTrainingMode( bool is_training ) {
    is_training_ = is_training;
}

// Decide on a trade offer after encoding the game state_______________________________________________________________

bool AIPlayer::decideOnTrade( TradeOffer trade_offer ) {
    arma::colvec state =
        Codec::encodeGameState( *players_, *board_, *playerPositions_, this, GamePhase::TRADE_RESPONSE );
    int offset = STATE_SIZE - TRADE_CONTEXT_SIZE;
    double cash_delta =
        static_cast<double>( trade_offer.cashRequested_ ) - static_cast<double>( trade_offer.cashOffered_ );
    state( offset ) = cash_delta / STARTING_CASH;
    ++offset;

    state( offset ) = ( trade_offer.cardOffered_ ) ? 1.0 : 0.0;
    ++offset;
    if( trade_offer.cardOffered_ ) {
        int idx = getPropertyIndex( trade_offer.cardOffered_ );
        if( idx >= 0 )
            state( offset + idx ) = 1.0;
    }
    offset += PROPERTIES;

    state( offset ) = ( trade_offer.cardRequested_ ) ? 1.0 : 0.0;
    ++offset;
    if( trade_offer.cardRequested_ ) {
        int idx = getPropertyIndex( trade_offer.cardRequested_ );
        if( idx >= 0 )
            state( offset + idx ) = 1.0;
    }
    unsigned int can_trade = ( getCash() >= trade_offer.cashRequested_ ) ? 1 : 0;

    arma::colvec action_mask =
        Codec::getActionMask( *players_, *board_, *playerPositions_, this, GamePhase::TRADE_RESPONSE, can_trade );
    unsigned int action_id = getDecisionFromBrain( state, action_mask, calculateReward() );

    return action_id == TRADE_ACCEPT_ID;
}

// Decide whether to propose a trade___________________________________________________________________________________

bool AIPlayer::wantsToTrade() {
    unsigned int action_id = getDecisionFromBrain( GamePhase::TRADE_PROPOSAL, calculateReward() );

    if( action_id == TRADE_DECLINE_ID ) {
        return false;
    }

    pending_trade_id_ = action_id;
    return true;
}

// Generate a trade offer based on the pending trade ID________________________________________________________________

TradeOffer AIPlayer::tradeOffer() {
    TradeOffer offer;

    if( pending_trade_id_ == UNDEFINED_ID ) {
        return offer;
    }
    PurchasableCard* target_card = nullptr;
    int curr_idx = 0;
    for( const auto& space : *board_ ) {
        if( auto* p_card = dynamic_cast<PurchasableCard*>( space->getAssociatedCard() ) ) {
            if( curr_idx == static_cast<int>( pending_trade_id_ - PROPOSE_TRADE_START_ID ) ) {
                target_card = p_card;
                break;
            }
            curr_idx++;
        }
    }

    if( target_card && target_card->getOwner() && target_card->getOwner() != this &&
        !target_card->getOwner()->isLost() ) {
        offer.receiver_ = target_card->getOwner();
        offer.cardRequested_ = target_card;
        double fair_price = static_cast<double>( target_card->getPrice() ) * TRADE_MULTIPLIER;
        if( fair_price < static_cast<double>( getCash() ) ) {
            offer.cashOffered_ = static_cast<unsigned int>( fair_price );
        } else {
            offer.cashOffered_ = getCash();
        }
    }

    pending_trade_id_ = UNDEFINED_ID;
    offer.requester_ = this;
    return offer;
}

// Helper method to retrieve a property by its index___________________________________________________________________

Property* AIPlayer::getPropertyByIndex( int index ) const {
    int count = 0;
    for( const auto& space : *board_ ) {
        if( auto* p = dynamic_cast<Property*>( space->getAssociatedCard() ) ) {
            if( count == index )
                return p;
            count++;
        }
    }
    return nullptr;
}

// Helper method to retrieve a purchasable card by its index___________________________________________________________

PurchasableCard* AIPlayer::getPurchasableByIndex( int index ) const {
    int count = 0;
    for( const auto& space : *board_ ) {
        if( auto* p = dynamic_cast<PurchasableCard*>( space->getAssociatedCard() ) ) {
            if( count == index )
                return p;
            count++;
        }
    }
    return nullptr;
}

// Helper method to retrieve the index of a property___________________________________________________________________

int AIPlayer::getPropertyIndex( const PurchasableCard* target ) const {
    if( !target )
        return -1;
    int idx = 0;
    for( const auto& space : *board_ ) {
        if( space->getAssociatedCard() == target ) {
            return idx;
        }
        if( dynamic_cast<PurchasableCard*>( space->getAssociatedCard() ) ) {
            idx++;
        }
    }
    return -1;
}